# Generated by Django 3.0.5 on 2020-05-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='title',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='DEFAULT NAME', max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='e_to',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='n_to',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='s_to',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='w_to',
            field=models.CharField(max_length=1),
        ),
    ]
