# Generated by Django 3.0.5 on 2020-05-01 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200501_1002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='currentRoom',
            new_name='current_room',
        ),
    ]
